config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home'
  

  get '/home', to: "static_pages#home"
  get '/map', to: "static_pages#map", as: :map
  
  get '/city/:cityname', to: "city#show", as: :city
  get '/static_maps/:longitude/:latitude', longitude: /[^\/]+/, latitude: /[^\/]+/, to: 'static_maps#show', as: :static_maps, defaults: { longitude:116.403874, latitude:39.914888 }
  get '/weather/:cityname', to: "weather#show", as: :weather
  get '/attractions/:attraction', to: "attractions#show", as: :attraction
  
  
  resources :users do
    resources :interest_points
    get "interest_points_create", to:"interest_points#create"
    get "interest_points_delete/:id", to:"interest_points#destroy", as:"interest_points_delete"
  end
  
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/reg', to: 'users#new'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  
  
end

app/views/layouts/_userform.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages'%>
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control'%>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control'%>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control'%>
    
    <%= f.submit "Create my account", class: "btn btn-primary" , style:"margin-top:10px"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %></title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all',
'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->
</head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
      <%= link_to "游必有方", map_path, id: "logo" %>
        <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "主页", map_path %></li>
          <% unless log_in?%>
            <li><%= link_to "登录", login_path %></li>
          <% else %>
            <li><%= link_to "欢迎，#{current_user.username}", logout_path %></li>
          <% end %>
        </ul>
        </nav>
      </div>
    </header>
    <div class="container" style="width:1300px">
      <%= yield %>
    </div>
  </body>
</html>